site_name: Brinton Memorial Cookbook
site_url: https://brintonmemorialcookbook.nl.ca/
site_description: This cookbook is dedicated to the students, parents and staff of Brinton Memorial School. March, 1996.
site_author: Brinton Memorial
copyright: '&copy; 1996 Brinton Memorial'
repo_name: mikew/brinton-memorial-cookbook
repo_url: https://github.com/mikew/brinton-memorial-cookbook

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://mikew.github.io/brinton-memorial-cookbook
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mikew/brinton-memorial-cookbook

plugins:
  - social
  - search

  # https://github.com/timvink/mkdocs-charts-plugin
  - charts

  # https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
  - awesome-pages:
      filename: navigation.yml

  # https://github.com/Andre601/mkdocs-pagenav-generator
  - pagenav-generator

  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/#configuration
  - tags

  # https://github.com/datarobot/mkdocs-redirects
  - redirects:
      redirects_maps:
        # 'old.md': new.md

  - glightbox

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.png
  favicon: assets/images/logo.png

  features:
    # Top level sections are always available at the top.
    - navigation.tabs
    # SPA navigation.
    - navigation.instant
    - navigation.indexes
    - navigation.footer
    # Move the table of contents for a page to the main sidebar.
    # - toc.integrate
    # Simple search suggestions as the user types.
    - search.suggest
    # Highlight what the user searched for.
    - search.highlight
    # All content tabs across the whole documentation site will be linked and
    # switch to the same label when the user clicks on a tab
    - content.tabs.link

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_javascript:
  # https://squidfunk.github.io/mkdocs-material/reference/mathjax/
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

  # https://github.com/timvink/mkdocs-charts-plugin
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

  # - https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js


extra_css:
  - assets/stylesheets/theme-overrides.css
  # - https://fonts.googleapis.com/css?family=Montserrat:300,400,700

markdown_extensions:
  - meta
  - pymdownx.betterem
  - pymdownx.smartsymbols

  - toc:
      permalink: true

  # https://squidfunk.github.io/mkdocs-material/reference/abbreviations/
  - abbr
  - pymdownx.snippets

  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # https://squidfunk.github.io/mkdocs-material/reference/annotations/
  - attr_list
  - md_in_html
  - pymdownx.superfences

  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#configuration
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  # https://squidfunk.github.io/mkdocs-material/reference/data-tables/
  - tables

  # https://squidfunk.github.io/mkdocs-material/reference/diagrams/
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        # https://github.com/timvink/mkdocs-charts-plugin
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite


  # https://squidfunk.github.io/mkdocs-material/reference/footnotes/
  - footnotes

  # https://squidfunk.github.io/mkdocs-material/reference/formatting/
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  # https://squidfunk.github.io/mkdocs-material/reference/images/
  - attr_list
  - md_in_html

  # https://squidfunk.github.io/mkdocs-material/reference/lists/
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  # https://squidfunk.github.io/mkdocs-material/reference/mathjax/
  - pymdownx.arithmatex:
      generic: true
